runtime: python39
entrypoint: gunicorn -b :$PORT src.myproject.wsgi

env_variables:
  DJANGO_SETTINGS_MODULE: "src.myproject.settings"

instance_class: F1

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto

beta_settings:
  cloud_sql_instances: rental-app-442220:us-west1:mysql-rental-instance 